#!/usr/bin/python3
"""
Chess Module - Games list test
Tests the /GAMES chess command
"""

import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
# All clients must be on the same server for chess to work
c1a = m.new('c1a')
c1b = m.new('c1b')
c1c = m.new('c1c')
m.connect()

# Test: Games listing
print("[TEST] Games list command")

# Start a game
m.send(c1a, "CHESS request $c1b 300")
m.clearlog()
m.send(c1b, "CHESS accept $c1a")
m.expect_all("Game starts", ":.*901.*")
m.clearlog()

# c1c requests games list
m.send(c1c, "GAMES chess")
m.expect(c1c, "Games list start", ":.*903.*")
m.expect(c1c, "Games list end", ":.*904.*")
m.clearlog()

# Cleanup
m.send(c1a, "CHESS resign")
m.clearlog()

print("Chess games list test passed!")

