#!/usr/bin/python3
"""
Chess Module - Basic functionality tests
Tests chess game request, accept, and basic moves
"""

import irctestframework.irctest

m = irctestframework.irctest.IrcTest()
# All clients must be on the same server for chess to work
c1a = m.new('c1a', '1')
c2a = m.new('c2a', '1')
c3a = m.new('c3a', '1')
m.connect()

# Test 1: Chess game request
print("[TEST] Chess game request")
m.send(c1a, "CHESS request $c2a 300")
m.expect(c2a, "c2a receives game request", ":.*900.*:.*challenges you to a chess game")
m.expect(c1a, "c1a gets confirmation", "NOTICE.*request sent")
m.clearlog()
print()

# Test 2: Chess game accept
print("[TEST] Chess game accept")
m.send(c2a, "CHESS accept $c1a")
m.expect_all("Both players join game channel", "JOIN #chess-")
m.expect_all("Game start notification", ":.*901.*")
m.expect(c1a, "c1a gets chess player mode", "MODE.*\\+c")
m.expect(c2a, "c2a gets chess player mode", "MODE.*\\+c")
m.clearlog()
print()

# Test 3: Valid chess move (White's first move)
print("[TEST] Valid chess move")
m.send(c1a, "CHESSMOVE e4")
m.expect_all("Move notification", ":.*920.*e4")
m.clearlog()
print()

# Test 4: Black's response
print("[TEST] Black's move")
m.send(c2a, "CHESSMOVE e5")
m.expect_all("Move notification", ":.*920.*e5")
m.clearlog()
print()

# Test 5: Another valid move
print("[TEST] Knight move")
m.send(c1a, "CHESSMOVE Nf3")
m.expect_all("Knight move notification", ":.*920.*Nf3")
m.clearlog()
print()

# Test 6: Invalid move (wrong turn)
print("[TEST] Wrong turn")
m.send(c1a, "CHESSMOVE Bc4")
m.expect(c1a, "Wrong turn error", ":.*942.*")
m.clearlog()
print()

# Test 7: Valid black move
print("[TEST] Black knight move")
m.send(c2a, "CHESSMOVE Nc6")
m.expect_all("Move notification", ":.*920.*Nc6")
m.clearlog()
print()

# Test 8: Board display
print("[TEST] Board display")
m.send(c1a, "CHESSBOARD")
m.expect(c1a, "Board display received", ":.*910.*")
m.clearlog()
print()

# Test 9: Chess clock
print("[TEST] Chess clock")
m.send(c1a, "CHESSCLOCK")
m.expect(c1a, "Timer info received", ":.*930.*")
m.clearlog()
print()

# Test 10: Game resignation
print("[TEST] Game resignation")
m.send(c1a, "CHESS resign")
m.expect_all("Game end notification", ":.*902.*")
m.expect(c1a, "Chess player mode removed", "MODE.*-c")
m.expect(c2a, "Chess player mode removed", "MODE.*-c")
m.clearlog()
print()

# Test 11: Game decline
print("[TEST] Game decline")
m.send(c1a, "CHESS request $c2a 300")
m.expect(c2a, "c2a receives game request", ":.*900.*")
m.clearlog()
m.send(c2a, "CHESS decline $c1a")
m.expect(c1a, "c1a notified of decline", "NOTICE.*declined")
m.clearlog()
print()

# Test 12: Observer can join game channel
print("[TEST] Observer mode")
# First start a game between c1a and c2a
m.send(c1a, "CHESS request $c2a 300")
m.clearlog()
m.send(c2a, "CHESS accept $c1a")
m.expect_all("Game starts", ":.*901.*")
m.clearlog()

# c3a tries to observe
m.send(c3a, "JOIN #chess-$c1a-$c2a")
m.expect(c3a, "Observer joins", "JOIN #chess-")
m.clearlog()

# Enable observer chat
m.send(c3a, "CHESSOBSERVER")
m.expect(c3a, "Observer mode enabled", "NOTICE.*observer")
m.clearlog()

# Cleanup - resign the game
m.send(c1a, "CHESS resign")
m.clearlog()
print()

print("All chess basic tests passed!")

